SELECT S.USN,S.SNAME,S.ADDRESS,S.PHONE,S.GENDER FROM STUDENT S,CLASS C,SEMSEC SS WHERE S.USN=C.USN AND SS.SSID=C.SSID AND SS.SEM=4 AND SS.SEC='C';

SELECT SS.SEM,SS.SEC,S.GENDER,COUNT(S.GENDER) FROM STUDENT S,SEMSEC SS,CLASS C WHERE S.USN=C.USN AND SS.SSID=C.SSID GROUP BY SS.SEM,SS.SEC,S.GENDER;

CREATE VIEW TEST1_MARKS AS SELECT USN,SUBCODE,TEST1 FROM IAMARKS WHERE USN='1MV17IS091';

SELECT * FROM TEST1_MARKS;

SELECT * FROM IAMARKS;


CREATE OR REPLACE PROCEDURE AVGMARKS IS CURSOR C_IAMARKS IS
SELECT GREATEST(TEST1,TEST2) AS A,GREATEST(TEST1,TEST3) AS B,GREATEST(TEST2,TEST3) AS C FROM IAMARKS
WHERE FINALIA IS NULL
 FOR UPDATE;
 C_A NUMBER;
 C_B NUMBER;
 C_C NUMBER;
 C_SUM NUMBER;
 C_AVG NUMBER;
 BEGIN
 OPEN C_IAMARKS;
 LOOP
 FETCH C_IAMARKS INTO C_A,C_B,C_C;
 EXIT WHEN C_IAMARKS%NOTFOUND;
 DBMS_OUTPUT.PUT_LINE(C_A||''||C_B||''||C_C);
 IF(C_A!=C_B) THEN
 C_SUM:=C_A+C_B;
 ELSE
 C_SUM:=C_A+C_C;
 END IF;
 C_AVG:=C_SUM/2;
 DBMS_OUTPUT.PUT_LINE('SUM='||C_SUM);
 DBMS_OUTPUT.PUT_LINE('AVERAGE='||C_AVG);
 UPDATE IAMARKS SET FINALIA=C_AVG
 WHERE CURRENT OF C_IAMARKS;
 END LOOP;
 CLOSE C_IAMARKS;
 END;
 /

BEGIN AVGMARKS;
END;
/

 SELECT * FROM IAMARKS;

 SELECT S.USN,S.SNAME,S.ADDRESS,S.PHONE,S.GENDER, ( CASE WHEN IA.FINALIA BETWEEN 17 AND 20 THEN 'OUTSTANDING' WHEN IA.FINALIA BETWEEN 12 AND 16 THEN 'AVERAGE' ELSE 'WEAK' END )
 AS CAT FROM STUDENT S,SEMSEC SS,IAMARKS IA WHERE S.USN=IA.USN AND SS.SSID=IA.SSID AND SS.SEM=8;
