SELECT B.BOOK_ID, B.TITLE, B.PUBLISHER_NAME, A.AUTHOR_NAME, C.NO_OF_COPIES, L.BRANCH_ID FROM BOOK B, BOOK_AUTHORS A, BOOK_COPIES C, LIBRARY_BRANCH L WHERE B.BOOK_ID=A.BOOK_ID AND B.BOOK_ID=C.BOOK_ID AND L.BRANCH_ID=C.BRANCH_ID;

SELECT CARD_NO FROM BOOK_LENDING WHERE DATE_OUT BETWEEN '01-JAN-2017' AND '01-JUL-2017' GROUP BY CARD_NO HAVING COUNT (*)>3;

SELECT * FROM BOOK;

DELETE FROM BOOK WHERE BOOK_ID=3;

SELECT * FROM BOOK;

CREATE VIEW V_PUBLICATION AS SELECT PUB_YEAR FROM BOOK;

SELECT * FROM V_PUBLICATION;

CREATE VIEW V_BOOKS AS SELECT B.BOOK_ID, B.TITLE, C.NO_OF_COPIES FROM BOOK B, BOOK_COPIES C, LIBRARY_BRANCH L WHERE B.BOOK_ID=C.BOOK_ID AND C.BRANCH_ID=L.BRANCH_ID;

SELECT * FROM V_BOOKS;
