CREATE TABLE DEPARTMENT (DNO VARCHAR (20) PRIMARY KEY, DNAME VARCHAR (20), MGRSTARTDATE DATE);

CREATE TABLE EMPLOYEE (SSN VARCHAR (20) PRIMARY KEY, FNAME VARCHAR (20), LNAME VARCHAR (20), ADDRESS VARCHAR (20), SEX CHAR (1), SALARY NUMBER, SUPERSSN REFERENCES EMPLOYEE (SSN), DNO REFERENCES DEPARTMENT (DNO));

ALTER TABLE DEPARTMENT ADD MGRSSN REFERENCES EMPLOYEE (SSN);

CREATE TABLE DLOCATION (DLOC VARCHAR (20), DNO REFERENCES DEPARTMENT (DNO), PRIMARY KEY (DNO, DLOC));

CREATE TABLE PROJECT (PNO NUMBER PRIMARY KEY, PNAME VARCHAR (20), PLOCATION VARCHAR (20), DNO REFERENCES DEPARTMENT (DNO));

CREATE TABLE WORKS_ON (HOURS NUMBER (2), SSN REFERENCES EMPLOYEE (SSN), PNO REFERENCES PROJECT(PNO), PRIMARY KEY (SSN, PNO));
